# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
user1 = User.create :name => "山田太郎", :email => "default1@sample.com", :password => "niodah89g2", :departmentId => 1
user2 = User.create :name => "小池雄二", :email => "default2@sample.com", :password => "niodah89g2", :departmentId => 2
user3 = User.create :name => "佐藤猛", :email => "default3@sample.com", :password => "niodah89g2", :departmentId => 3
user4 = User.create :name => "大林守", :email => "default4@sample.com", :password => "niodah89g2", :departmentId => 3
user5 = User.create :name => "清水雄太", :email => "default5@sample.com", :password => "niodah89g2", :departmentId => 3
departmentMaster1 = DepartmentMaster.create :name => "総務部", :enable => 1
departmentMaster2 = DepartmentMaster.create :name => "人事部", :enable => 1
departmentMaster3 = DepartmentMaster.create :name => "情報システム部" , :enable => 1
itemMaster1 = ItemMaster.create :name => "超硬ロングックスエアエドミル", :enable => 1
itemMaster2 = ItemMaster.create :name => "サホワト5 20W形", :enable => 1
itemMaster3 = ItemMaster.create :name => "70角型柱キャップ", :enable => 1
itemMaster4 = ItemMaster.create :name => "カー用 丸サバンド受", :enable => 1
itemMaster5 = ItemMaster.create :name => "ペーパー 工業用タイプ", :enable => 1
itemMaster6 = ItemMaster.create :name => "(90159)スクリウ", :enable => 1
itemMaster7 = ItemMaster.create :name => "絶縁 ギボシ", :enable => 1
itemMaster8 = ItemMaster.create :name => "カテゴリ6LANケーブル", :enable => 1
itemMaster9 = ItemMaster.create :name => "ノートパソコン収納", :enable => 1
itemMaster10 = ItemMaster.create :name => "ペーパー 工業用タイプ", :enable => 1
itemMaster11 = ItemMaster.create :name => "(8344)ブーツ，スイッチ", :enable => 1
itemMaster12 = ItemMaster.create :name => "コーセー ピュアマイルドリムーバーN", :enable => 1
itemMaster13 = ItemMaster.create :name => "70角型柱キャップ", :enable => 1
itemMaster14 = ItemMaster.create :name => "チューブフィッグストレート", :enable => 1
itemMaster15 = ItemMaster.create :name => "エクガン ハイパー", :enable => 1
itemMaster16 = ItemMaster.create :name => "切断砥石 両面補強 IS 径105mm×厚さ1.0mm", :enable => 1
itemMaster17 = ItemMaster.create :name => "2画面3色表力センサ MPS-35series", :enable => 1
itemMaster18 = ItemMaster.create :name => "2色表示式ースイッチ PFMB7", :enable => 1
itemMaster19 = ItemMaster.create :name => "ZSE(F)20/ISE20 - 3画チ(ISE20)", :enable => 1
itemMaster20 = ItemMaster.create :name => "研磨ベルト アルナ 幅100mm 長さ915mm", :enable => 1
stock1 = Stock.create :status => "入荷",:itemCode => 1,:registUser => 5,:updateUser => 2,:enable => 1
stock2 = Stock.create :status => "入荷",:itemCode => 3,:registUser => 3,:updateUser => 2,:enable => 1
stock3 = Stock.create :status => "棚卸",:itemCode => 5,:registUser => 3,:updateUser => 2,:enable => 1
stock4 = Stock.create :status => "返却",:itemCode => 1,:registUser => 5,:updateUser => 2,:enable => 1
stock5 = Stock.create :status => "不明",:itemCode => 3,:registUser => 5,:updateUser => 2,:enable => 1
stock6 = Stock.create :status => "不明",:itemCode => 1,:registUser => 3,:updateUser => 4,:enable => 1
stock7 = Stock.create :status => "返却",:itemCode => 2,:registUser => 3,:updateUser => 1,:enable => 1
stock8 = Stock.create :status => "返却",:itemCode => 15,:registUser => 1,:updateUser => 2,:enable => 1
stock9 = Stock.create :status => "返却",:itemCode => 5,:registUser => 4,:updateUser => 1,:enable => 1
stock10 = Stock.create :status => "棚卸",:itemCode => 1,:registUser => 2,:updateUser => 3,:enable => 1
stock11 = Stock.create :status => "棚卸",:itemCode => 5,:registUser => 2,:updateUser => 1,:enable => 1
stock12 = Stock.create :status => "処分",:itemCode => 3,:registUser => 2,:updateUser => 1,:enable => 1
stock13 = Stock.create :status => "棚卸",:itemCode => 14,:registUser => 1,:updateUser => 1,:enable => 1
stock14 = Stock.create :status => "入荷",:itemCode => 3,:registUser => 1,:updateUser => 3,:enable => 1
stock15 = Stock.create :status => "棚卸",:itemCode => 4,:registUser => 1,:updateUser => 3,:enable => 1
stock16 = Stock.create :status => "返却",:itemCode => 3,:registUser => 5,:updateUser => 2,:enable => 1
stock17 = Stock.create :status => "棚卸",:itemCode => 15,:registUser => 1,:updateUser => 4,:enable => 1
stock18 = Stock.create :status => "返却",:itemCode => 5,:registUser => 5,:updateUser => 5,:enable => 1
stock19 = Stock.create :status => "返却",:itemCode => 13,:registUser => 5,:updateUser => 3,:enable => 1
stock20 = Stock.create :status => "返却",:itemCode => 4,:registUser => 1,:updateUser => 2,:enable => 1
stock21 = Stock.create :status => "入荷",:itemCode => 4,:registUser => 5,:updateUser => 2,:enable => 1
stock22 = Stock.create :status => "不明",:itemCode => 5,:registUser => 2,:updateUser => 2,:enable => 1
stock23 = Stock.create :status => "不明",:itemCode => 15,:registUser => 1,:updateUser => 4,:enable => 1
stock24 = Stock.create :status => "棚卸",:itemCode => 4,:registUser => 1,:updateUser => 1,:enable => 1
stock25 = Stock.create :status => "返却",:itemCode => 11,:registUser => 1,:updateUser => 2,:enable => 1
stock26 = Stock.create :status => "処分",:itemCode => 2,:registUser => 5,:updateUser => 4,:enable => 1
stock27 = Stock.create :status => "入荷",:itemCode => 15,:registUser => 1,:updateUser => 5,:enable => 1
stock28 = Stock.create :status => "棚卸",:itemCode => 4,:registUser => 1,:updateUser => 4,:enable => 1
stock29 = Stock.create :status => "入荷",:itemCode => 1,:registUser => 1,:updateUser => 3,:enable => 1
stock30 = Stock.create :status => "不明",:itemCode => 2,:registUser => 2,:updateUser => 2,:enable => 1
stock31 = Stock.create :status => "不明",:itemCode => 12,:registUser => 1,:updateUser => 1,:enable => 1
stock32 = Stock.create :status => "棚卸",:itemCode => 5,:registUser => 3,:updateUser => 1,:enable => 1
stock33 = Stock.create :status => "返却",:itemCode => 4,:registUser => 4,:updateUser => 4,:enable => 1
stock34 = Stock.create :status => "不明",:itemCode => 2,:registUser => 2,:updateUser => 1,:enable => 1
stock35 = Stock.create :status => "処分",:itemCode => 12,:registUser => 3,:updateUser => 1,:enable => 1
stock36 = Stock.create :status => "不明",:itemCode => 3,:registUser => 1,:updateUser => 4,:enable => 1
stock37 = Stock.create :status => "処分",:itemCode => 1,:registUser => 5,:updateUser => 5,:enable => 1
stock38 = Stock.create :status => "棚卸",:itemCode => 12,:registUser => 2,:updateUser => 4,:enable => 1
stock39 = Stock.create :status => "返却",:itemCode => 15,:registUser => 2,:updateUser => 1,:enable => 1
stock40 = Stock.create :status => "不明",:itemCode => 11,:registUser => 3,:updateUser => 5,:enable => 1
stock41 = Stock.create :status => "処分",:itemCode => 3,:registUser => 3,:updateUser => 4,:enable => 1
stock42 = Stock.create :status => "不明",:itemCode => 3,:registUser => 4,:updateUser => 5,:enable => 1
stock43 = Stock.create :status => "入荷",:itemCode => 3,:registUser => 1,:updateUser => 3,:enable => 1
stock44 = Stock.create :status => "処分",:itemCode => 3,:registUser => 5,:updateUser => 1,:enable => 1
stock45 = Stock.create :status => "棚卸",:itemCode => 3,:registUser => 5,:updateUser => 3,:enable => 1
stock46 = Stock.create :status => "入荷",:itemCode => 6,:registUser => 4,:updateUser => 1,:enable => 1
stock47 = Stock.create :status => "不明",:itemCode => 9,:registUser => 1,:updateUser => 4,:enable => 1
stock48 = Stock.create :status => "入荷",:itemCode => 3,:registUser => 3,:updateUser => 1,:enable => 1
stock49 = Stock.create :status => "不明",:itemCode => 3,:registUser => 4,:updateUser => 5,:enable => 1
stock50 = Stock.create :status => "返却",:itemCode => 7,:registUser => 4,:updateUser => 2,:enable => 1
stock51 = Stock.create :status => "棚卸",:itemCode => 3,:registUser => 1,:updateUser => 1,:enable => 1
stock52 = Stock.create :status => "入荷",:itemCode => 1,:registUser => 4,:updateUser => 2,:enable => 1
stock53 = Stock.create :status => "処分",:itemCode => 5,:registUser => 2,:updateUser => 2,:enable => 1
stock54 = Stock.create :status => "不明",:itemCode => 4,:registUser => 3,:updateUser => 5,:enable => 1
stock55 = Stock.create :status => "入荷",:itemCode => 3,:registUser => 3,:updateUser => 3,:enable => 1
stock56 = Stock.create :status => "棚卸",:itemCode => 4,:registUser => 2,:updateUser => 1,:enable => 1
stock57 = Stock.create :status => "入荷",:itemCode => 1,:registUser => 3,:updateUser => 5,:enable => 1
stock58 = Stock.create :status => "処分",:itemCode => 3,:registUser => 5,:updateUser => 3,:enable => 1
stock59 = Stock.create :status => "棚卸",:itemCode => 8,:registUser => 1,:updateUser => 1,:enable => 1
stock60 = Stock.create :status => "入荷",:itemCode => 5,:registUser => 1,:updateUser => 2,:enable => 1
stock61 = Stock.create :status => "入荷",:itemCode => 3,:registUser => 1,:updateUser => 1,:enable => 1
stock62 = Stock.create :status => "返却",:itemCode => 8,:registUser => 3,:updateUser => 5,:enable => 1
stock63 = Stock.create :status => "入荷",:itemCode => 5,:registUser => 1,:updateUser => 2,:enable => 1
stock64 = Stock.create :status => "処分",:itemCode => 5,:registUser => 1,:updateUser => 5,:enable => 1
stock65 = Stock.create :status => "返却",:itemCode => 3,:registUser => 1,:updateUser => 3,:enable => 1
stock66 = Stock.create :status => "処分",:itemCode => 5,:registUser => 2,:updateUser => 2,:enable => 1
stock67 = Stock.create :status => "棚卸",:itemCode => 1,:registUser => 2,:updateUser => 1,:enable => 1
stock68 = Stock.create :status => "棚卸",:itemCode => 5,:registUser => 4,:updateUser => 3,:enable => 1
stock69 = Stock.create :status => "不明",:itemCode => 3,:registUser => 4,:updateUser => 3,:enable => 1
stock70 = Stock.create :status => "入荷",:itemCode => 1,:registUser => 4,:updateUser => 3,:enable => 1
stock71 = Stock.create :status => "不明",:itemCode => 4,:registUser => 5,:updateUser => 1,:enable => 1
stock72 = Stock.create :status => "入荷",:itemCode => 3,:registUser => 1,:updateUser => 4,:enable => 1
stock73 = Stock.create :status => "不明",:itemCode => 8,:registUser => 3,:updateUser => 3,:enable => 1
stock74 = Stock.create :status => "棚卸",:itemCode => 2,:registUser => 1,:updateUser => 2,:enable => 1
stock75 = Stock.create :status => "棚卸",:itemCode => 3,:registUser => 5,:updateUser => 4,:enable => 1
stock76 = Stock.create :status => "処分",:itemCode => 8,:registUser => 2,:updateUser => 1,:enable => 1
stock77 = Stock.create :status => "不明",:itemCode => 5,:registUser => 4,:updateUser => 2,:enable => 1
stock78 = Stock.create :status => "入荷",:itemCode => 3,:registUser => 3,:updateUser => 1,:enable => 1
stock79 = Stock.create :status => "処分",:itemCode => 8,:registUser => 4,:updateUser => 5,:enable => 1
stock80 = Stock.create :status => "棚卸",:itemCode => 3,:registUser => 2,:updateUser => 1,:enable => 1
stock81 = Stock.create :status => "処分",:itemCode => 4,:registUser => 4,:updateUser => 1,:enable => 1
stock82 = Stock.create :status => "返却",:itemCode => 3,:registUser => 4,:updateUser => 4,:enable => 1
stock83 = Stock.create :status => "不明",:itemCode => 8,:registUser => 4,:updateUser => 3,:enable => 1
stock84 = Stock.create :status => "棚卸",:itemCode => 5,:registUser => 2,:updateUser => 4,:enable => 1
stock85 = Stock.create :status => "棚卸",:itemCode => 5,:registUser => 5,:updateUser => 2,:enable => 1
stock86 = Stock.create :status => "棚卸",:itemCode => 6,:registUser => 5,:updateUser => 3,:enable => 1
stock87 = Stock.create :status => "処分",:itemCode => 18,:registUser => 1,:updateUser => 4,:enable => 1
stock88 = Stock.create :status => "返却",:itemCode => 5,:registUser => 3,:updateUser => 5,:enable => 1
stock89 = Stock.create :status => "棚卸",:itemCode => 17,:registUser => 2,:updateUser => 5,:enable => 1
stock90 = Stock.create :status => "入荷",:itemCode => 4,:registUser => 3,:updateUser => 4,:enable => 1
stock91 = Stock.create :status => "不明",:itemCode => 18,:registUser => 1,:updateUser => 2,:enable => 1
stock92 = Stock.create :status => "返却",:itemCode => 4,:registUser => 3,:updateUser => 3,:enable => 1
stock93 = Stock.create :status => "入荷",:itemCode => 5,:registUser => 5,:updateUser => 5,:enable => 1
stock94 = Stock.create :status => "処分",:itemCode => 19,:registUser => 5,:updateUser => 1,:enable => 1
stock95 = Stock.create :status => "不明",:itemCode => 3,:registUser => 4,:updateUser => 5,:enable => 1
stock96 = Stock.create :status => "不明",:itemCode => 1,:registUser => 1,:updateUser => 4,:enable => 1
stock97 = Stock.create :status => "棚卸",:itemCode => 3,:registUser => 3,:updateUser => 2,:enable => 1
stock98 = Stock.create :status => "処分",:itemCode => 6,:registUser => 4,:updateUser => 2,:enable => 1
stock99 = Stock.create :status => "処分",:itemCode => 5,:registUser => 1,:updateUser => 3,:enable => 1
stock100 = Stock.create :status => "処分",:itemCode => 15,:registUser => 5,:updateUser => 1,:enable => 1
stock101 = Stock.create :status => "棚卸",:itemCode => 2,:registUser => 5,:updateUser => 2,:enable => 1
stock102 = Stock.create :status => "入荷",:itemCode => 3,:registUser => 5,:updateUser => 3,:enable => 1
stock103 = Stock.create :status => "棚卸",:itemCode => 4,:registUser => 3,:updateUser => 1,:enable => 1
stock104 = Stock.create :status => "処分",:itemCode => 5,:registUser => 1,:updateUser => 3,:enable => 1
stock105 = Stock.create :status => "棚卸",:itemCode => 2,:registUser => 5,:updateUser => 2,:enable => 1
stock106 = Stock.create :status => "不明",:itemCode => 2,:registUser => 1,:updateUser => 4,:enable => 1
stock107 = Stock.create :status => "不明",:itemCode => 2,:registUser => 4,:updateUser => 3,:enable => 1
stock108 = Stock.create :status => "入荷",:itemCode => 11,:registUser => 3,:updateUser => 3,:enable => 1
stock109 = Stock.create :status => "入荷",:itemCode => 1,:registUser => 2,:updateUser => 2,:enable => 1
stock110 = Stock.create :status => "入荷",:itemCode => 16,:registUser => 5,:updateUser => 3,:enable => 1
stock111 = Stock.create :status => "不明",:itemCode => 4,:registUser => 3,:updateUser => 4,:enable => 1
stock112 = Stock.create :status => "不明",:itemCode => 4,:registUser => 5,:updateUser => 1,:enable => 1
stock113 = Stock.create :status => "処分",:itemCode => 1,:registUser => 2,:updateUser => 2,:enable => 1
stock114 = Stock.create :status => "返却",:itemCode => 2,:registUser => 5,:updateUser => 2,:enable => 1
stock115 = Stock.create :status => "入荷",:itemCode => 3,:registUser => 4,:updateUser => 5,:enable => 1
stock116 = Stock.create :status => "入荷",:itemCode => 4,:registUser => 2,:updateUser => 4,:enable => 1
stock117 = Stock.create :status => "不明",:itemCode => 19,:registUser => 3,:updateUser => 3,:enable => 1
stock118 = Stock.create :status => "入荷",:itemCode => 3,:registUser => 4,:updateUser => 4,:enable => 1
stock119 = Stock.create :status => "不明",:itemCode => 16,:registUser => 2,:updateUser => 2,:enable => 1
stock120 = Stock.create :status => "棚卸",:itemCode => 4,:registUser => 4,:updateUser => 4,:enable => 1
stock121 = Stock.create :status => "返却",:itemCode => 15,:registUser => 3,:updateUser => 4,:enable => 1
stock122 = Stock.create :status => "棚卸",:itemCode => 3,:registUser => 5,:updateUser => 5,:enable => 1
stock123 = Stock.create :status => "不明",:itemCode => 1,:registUser => 3,:updateUser => 4,:enable => 1
stock124 = Stock.create :status => "処分",:itemCode => 14,:registUser => 5,:updateUser => 3,:enable => 1
stock125 = Stock.create :status => "不明",:itemCode => 3,:registUser => 1,:updateUser => 5,:enable => 1
stock126 = Stock.create :status => "入荷",:itemCode => 5,:registUser => 4,:updateUser => 4,:enable => 1
stock127 = Stock.create :status => "返却",:itemCode => 12,:registUser => 1,:updateUser => 4,:enable => 1
stock128 = Stock.create :status => "処分",:itemCode => 1,:registUser => 3,:updateUser => 3,:enable => 1
stock129 = Stock.create :status => "不明",:itemCode => 3,:registUser => 2,:updateUser => 3,:enable => 1
stock130 = Stock.create :status => "返却",:itemCode => 15,:registUser => 5,:updateUser => 2,:enable => 1
stock131 = Stock.create :status => "棚卸",:itemCode => 1,:registUser => 4,:updateUser => 1,:enable => 1
stock132 = Stock.create :status => "不明",:itemCode => 4,:registUser => 5,:updateUser => 3,:enable => 1
stock133 = Stock.create :status => "棚卸",:itemCode => 12,:registUser => 2,:updateUser => 5,:enable => 1
stock134 = Stock.create :status => "不明",:itemCode => 3,:registUser => 4,:updateUser => 3,:enable => 1
stock135 = Stock.create :status => "入荷",:itemCode => 2,:registUser => 5,:updateUser => 2,:enable => 1
stock136 = Stock.create :status => "処分",:itemCode => 11,:registUser => 5,:updateUser => 4,:enable => 1
stock137 = Stock.create :status => "不明",:itemCode => 1,:registUser => 5,:updateUser => 3,:enable => 1
stock138 = Stock.create :status => "棚卸",:itemCode => 5,:registUser => 1,:updateUser => 5,:enable => 1
stock139 = Stock.create :status => "入荷",:itemCode => 13,:registUser => 3,:updateUser => 3,:enable => 1
stock140 = Stock.create :status => "不明",:itemCode => 3,:registUser => 3,:updateUser => 5,:enable => 1
stock141 = Stock.create :status => "入荷",:itemCode => 5,:registUser => 5,:updateUser => 5,:enable => 1
stock142 = Stock.create :status => "返却",:itemCode => 11,:registUser => 3,:updateUser => 4,:enable => 1
stock143 = Stock.create :status => "不明",:itemCode => 2,:registUser => 5,:updateUser => 3,:enable => 1
stock144 = Stock.create :status => "棚卸",:itemCode => 16,:registUser => 3,:updateUser => 5,:enable => 1
stock145 = Stock.create :status => "入荷",:itemCode => 2,:registUser => 3,:updateUser => 3,:enable => 1
stock146 = Stock.create :status => "入荷",:itemCode => 17,:registUser => 3,:updateUser => 3,:enable => 1
stock147 = Stock.create :status => "棚卸",:itemCode => 3,:registUser => 1,:updateUser => 2,:enable => 1
stock148 = Stock.create :status => "棚卸",:itemCode => 3,:registUser => 2,:updateUser => 4,:enable => 1
stock149 = Stock.create :status => "不明",:itemCode => 1,:registUser => 4,:updateUser => 2,:enable => 1
stock150 = Stock.create :status => "不明",:itemCode => 18,:registUser => 4,:updateUser => 4,:enable => 1
stock151 = Stock.create :status => "入荷",:itemCode => 3,:registUser => 4,:updateUser => 1,:enable => 1
stock152 = Stock.create :status => "処分",:itemCode => 1,:registUser => 1,:updateUser => 5,:enable => 1
stock153 = Stock.create :status => "棚卸",:itemCode => 14,:registUser => 2,:updateUser => 1,:enable => 1
stock154 = Stock.create :status => "不明",:itemCode => 2,:registUser => 1,:updateUser => 1,:enable => 1
stock155 = Stock.create :status => "処分",:itemCode => 3,:registUser => 1,:updateUser => 1,:enable => 1
stock156 = Stock.create :status => "処分",:itemCode => 2,:registUser => 3,:updateUser => 3,:enable => 1
stock157 = Stock.create :status => "返却",:itemCode => 4,:registUser => 5,:updateUser => 2,:enable => 1
stock158 = Stock.create :status => "返却",:itemCode => 15,:registUser => 3,:updateUser => 2,:enable => 1
stock159 = Stock.create :status => "処分",:itemCode => 11,:registUser => 4,:updateUser => 5,:enable => 1
stock160 = Stock.create :status => "棚卸",:itemCode => 15,:registUser => 1,:updateUser => 2,:enable => 1
stock161 = Stock.create :status => "棚卸",:itemCode => 12,:registUser => 1,:updateUser => 5,:enable => 1
stock162 = Stock.create :status => "返却",:itemCode => 14,:registUser => 4,:updateUser => 3,:enable => 1
stock163 = Stock.create :status => "処分",:itemCode => 11,:registUser => 2,:updateUser => 1,:enable => 1
stock164 = Stock.create :status => "棚卸",:itemCode => 14,:registUser => 2,:updateUser => 5,:enable => 1
stock165 = Stock.create :status => "処分",:itemCode => 13,:registUser => 4,:updateUser => 4,:enable => 1
stock166 = Stock.create :status => "返却",:itemCode => 4,:registUser => 2,:updateUser => 4,:enable => 1
stock167 = Stock.create :status => "返却",:itemCode => 5,:registUser => 3,:updateUser => 5,:enable => 1
stock168 = Stock.create :status => "入荷",:itemCode => 1,:registUser => 2,:updateUser => 2,:enable => 1
stock169 = Stock.create :status => "処分",:itemCode => 5,:registUser => 2,:updateUser => 5,:enable => 1
stock170 = Stock.create :status => "棚卸",:itemCode => 1,:registUser => 1,:updateUser => 2,:enable => 1
stock171 = Stock.create :status => "処分",:itemCode => 2,:registUser => 3,:updateUser => 3,:enable => 1
stock172 = Stock.create :status => "処分",:itemCode => 4,:registUser => 1,:updateUser => 1,:enable => 1
stock173 = Stock.create :status => "入荷",:itemCode => 14,:registUser => 2,:updateUser => 3,:enable => 1
stock174 = Stock.create :status => "棚卸",:itemCode => 5,:registUser => 1,:updateUser => 1,:enable => 1
stock175 = Stock.create :status => "入荷",:itemCode => 15,:registUser => 2,:updateUser => 4,:enable => 1
stock176 = Stock.create :status => "返却",:itemCode => 1,:registUser => 2,:updateUser => 4,:enable => 1
stock177 = Stock.create :status => "処分",:itemCode => 6,:registUser => 4,:updateUser => 4,:enable => 1
stock178 = Stock.create :status => "入荷",:itemCode => 7,:registUser => 4,:updateUser => 3,:enable => 1
stock179 = Stock.create :status => "返却",:itemCode => 8,:registUser => 3,:updateUser => 3,:enable => 1
stock180 = Stock.create :status => "不明",:itemCode => 2,:registUser => 5,:updateUser => 5,:enable => 1
stock181 = Stock.create :status => "棚卸",:itemCode => 9,:registUser => 4,:updateUser => 1,:enable => 1
stock182 = Stock.create :status => "処分",:itemCode => 3,:registUser => 1,:updateUser => 3,:enable => 1
stock183 = Stock.create :status => "入荷",:itemCode => 11,:registUser => 1,:updateUser => 5,:enable => 1
stock184 = Stock.create :status => "処分",:itemCode => 6,:registUser => 4,:updateUser => 4,:enable => 1
stock185 = Stock.create :status => "処分",:itemCode => 3,:registUser => 2,:updateUser => 3,:enable => 1
stock186 = Stock.create :status => "返却",:itemCode => 7,:registUser => 1,:updateUser => 2,:enable => 1
stock187 = Stock.create :status => "棚卸",:itemCode => 5,:registUser => 2,:updateUser => 5,:enable => 1
stock188 = Stock.create :status => "返却",:itemCode => 8,:registUser => 1,:updateUser => 5,:enable => 1
stock189 = Stock.create :status => "返却",:itemCode => 3,:registUser => 4,:updateUser => 2,:enable => 1
stock190 = Stock.create :status => "不明",:itemCode => 5,:registUser => 2,:updateUser => 4,:enable => 1
stock191 = Stock.create :status => "入荷",:itemCode => 4,:registUser => 4,:updateUser => 3,:enable => 1
stock192 = Stock.create :status => "棚卸",:itemCode => 9,:registUser => 5,:updateUser => 5,:enable => 1
stock193 = Stock.create :status => "返却",:itemCode => 3,:registUser => 1,:updateUser => 2,:enable => 1
stock194 = Stock.create :status => "不明",:itemCode => 19,:registUser => 3,:updateUser => 2,:enable => 1
stock195 = Stock.create :status => "不明",:itemCode => 2,:registUser => 2,:updateUser => 4,:enable => 1
stock196 = Stock.create :status => "不明",:itemCode => 2,:registUser => 3,:updateUser => 5,:enable => 1
stock197 = Stock.create :status => "返却",:itemCode => 4,:registUser => 2,:updateUser => 3,:enable => 1
stock198 = Stock.create :status => "返却",:itemCode => 14,:registUser => 2,:updateUser => 5,:enable => 1
stock199 = Stock.create :status => "返却",:itemCode => 2,:registUser => 5,:updateUser => 5,:enable => 1
stock200 = Stock.create :status => "棚卸",:itemCode => 1,:registUser => 2,:updateUser => 4,:enable => 1
stock201 = Stock.create :status => "返却",:itemCode => 12,:registUser => 5,:updateUser => 2,:enable => 1
stock202 = Stock.create :status => "棚卸",:itemCode => 11,:registUser => 5,:updateUser => 1,:enable => 1
stock203 = Stock.create :status => "入荷",:itemCode => 1,:registUser => 3,:updateUser => 3,:enable => 1
stock204 = Stock.create :status => "棚卸",:itemCode => 14,:registUser => 2,:updateUser => 1,:enable => 1
stock205 = Stock.create :status => "入荷",:itemCode => 3,:registUser => 5,:updateUser => 1,:enable => 1
stock206 = Stock.create :status => "不明",:itemCode => 12,:registUser => 2,:updateUser => 1,:enable => 1
stock207 = Stock.create :status => "不明",:itemCode => 2,:registUser => 4,:updateUser => 1,:enable => 1
stock208 = Stock.create :status => "不明",:itemCode => 2,:registUser => 4,:updateUser => 2,:enable => 1
stock209 = Stock.create :status => "処分",:itemCode => 15,:registUser => 4,:updateUser => 1,:enable => 1
stock210 = Stock.create :status => "不明",:itemCode => 2,:registUser => 4,:updateUser => 3,:enable => 1
stock211 = Stock.create :status => "処分",:itemCode => 2,:registUser => 1,:updateUser => 1,:enable => 1
stock212 = Stock.create :status => "処分",:itemCode => 13,:registUser => 3,:updateUser => 5,:enable => 1
stock213 = Stock.create :status => "返却",:itemCode => 3,:registUser => 3,:updateUser => 3,:enable => 1
stock214 = Stock.create :status => "棚卸",:itemCode => 2,:registUser => 1,:updateUser => 3,:enable => 1
stock215 = Stock.create :status => "棚卸",:itemCode => 15,:registUser => 3,:updateUser => 5,:enable => 1
stock216 = Stock.create :status => "不明",:itemCode => 1,:registUser => 4,:updateUser => 2,:enable => 1
stock217 = Stock.create :status => "処分",:itemCode => 2,:registUser => 3,:updateUser => 5,:enable => 1
stock218 = Stock.create :status => "不明",:itemCode => 12,:registUser => 3,:updateUser => 5,:enable => 1
stock219 = Stock.create :status => "入荷",:itemCode => 4,:registUser => 5,:updateUser => 3,:enable => 1
stock220 = Stock.create :status => "不明",:itemCode => 4,:registUser => 3,:updateUser => 2,:enable => 1
stock221 = Stock.create :status => "棚卸",:itemCode => 11,:registUser => 2,:updateUser => 3,:enable => 1
stock222 = Stock.create :status => "入荷",:itemCode => 5,:registUser => 3,:updateUser => 1,:enable => 1
stock223 = Stock.create :status => "処分",:itemCode => 5,:registUser => 4,:updateUser => 5,:enable => 1
stock224 = Stock.create :status => "処分",:itemCode => 11,:registUser => 5,:updateUser => 2,:enable => 1
stock225 = Stock.create :status => "不明",:itemCode => 4,:registUser => 4,:updateUser => 3,:enable => 1
stock226 = Stock.create :status => "入荷",:itemCode => 2,:registUser => 3,:updateUser => 1,:enable => 1
stock227 = Stock.create :status => "棚卸",:itemCode => 3,:registUser => 3,:updateUser => 2,:enable => 1
stock228 = Stock.create :status => "不明",:itemCode => 2,:registUser => 3,:updateUser => 3,:enable => 1
stock229 = Stock.create :status => "返却",:itemCode => 4,:registUser => 2,:updateUser => 3,:enable => 1
stock230 = Stock.create :status => "棚卸",:itemCode => 11,:registUser => 2,:updateUser => 3,:enable => 1
stock231 = Stock.create :status => "返却",:itemCode => 3,:registUser => 3,:updateUser => 1,:enable => 1
stock232 = Stock.create :status => "処分",:itemCode => 5,:registUser => 5,:updateUser => 5,:enable => 1
stock233 = Stock.create :status => "不明",:itemCode => 13,:registUser => 3,:updateUser => 5,:enable => 1
stock234 = Stock.create :status => "処分",:itemCode => 2,:registUser => 1,:updateUser => 3,:enable => 1
stock235 = Stock.create :status => "入荷",:itemCode => 4,:registUser => 1,:updateUser => 1,:enable => 1
stock236 = Stock.create :status => "処分",:itemCode => 1,:registUser => 3,:updateUser => 1,:enable => 1
stock237 = Stock.create :status => "返却",:itemCode => 14,:registUser => 3,:updateUser => 5,:enable => 1
stock238 = Stock.create :status => "入荷",:itemCode => 4,:registUser => 2,:updateUser => 5,:enable => 1
stock239 = Stock.create :status => "返却",:itemCode => 1,:registUser => 2,:updateUser => 1,:enable => 1
stock240 = Stock.create :status => "処分",:itemCode => 11,:registUser => 5,:updateUser => 5,:enable => 1
stock241 = Stock.create :status => "返却",:itemCode => 5,:registUser => 5,:updateUser => 1,:enable => 1
stock242 = Stock.create :status => "返却",:itemCode => 5,:registUser => 5,:updateUser => 4,:enable => 1
stock243 = Stock.create :status => "返却",:itemCode => 11,:registUser => 2,:updateUser => 4,:enable => 1
stock244 = Stock.create :status => "処分",:itemCode => 2,:registUser => 4,:updateUser => 3,:enable => 1
stock245 = Stock.create :status => "不明",:itemCode => 3,:registUser => 3,:updateUser => 3,:enable => 1
stock246 = Stock.create :status => "不明",:itemCode => 14,:registUser => 4,:updateUser => 4,:enable => 1
stock247 = Stock.create :status => "入荷",:itemCode => 3,:registUser => 2,:updateUser => 5,:enable => 1
stock248 = Stock.create :status => "返却",:itemCode => 4,:registUser => 4,:updateUser => 5,:enable => 1
stock249 = Stock.create :status => "入荷",:itemCode => 11,:registUser => 2,:updateUser => 2,:enable => 1
stock250 = Stock.create :status => "処分",:itemCode => 4,:registUser => 3,:updateUser => 4,:enable => 1
stock251 = Stock.create :status => "棚卸",:itemCode => 1,:registUser => 5,:updateUser => 5,:enable => 1
stock252 = Stock.create :status => "不明",:itemCode => 14,:registUser => 5,:updateUser => 3,:enable => 1
stock253 = Stock.create :status => "処分",:itemCode => 2,:registUser => 2,:updateUser => 4,:enable => 1
stock254 = Stock.create :status => "処分",:itemCode => 3,:registUser => 3,:updateUser => 3,:enable => 1
stock255 = Stock.create :status => "入荷",:itemCode => 13,:registUser => 3,:updateUser => 5,:enable => 1
stock256 = Stock.create :status => "不明",:itemCode => 4,:registUser => 5,:updateUser => 2,:enable => 1
stock257 = Stock.create :status => "返却",:itemCode => 5,:registUser => 1,:updateUser => 5,:enable => 1
stock258 = Stock.create :status => "処分",:itemCode => 13,:registUser => 2,:updateUser => 2,:enable => 1
stock259 = Stock.create :status => "処分",:itemCode => 3,:registUser => 3,:updateUser => 4,:enable => 1
stock260 = Stock.create :status => "返却",:itemCode => 3,:registUser => 4,:updateUser => 3,:enable => 1
stock261 = Stock.create :status => "処分",:itemCode => 14,:registUser => 2,:updateUser => 4,:enable => 1
stock262 = Stock.create :status => "処分",:itemCode => 14,:registUser => 4,:updateUser => 1,:enable => 1
stock263 = Stock.create :status => "不明",:itemCode => 12,:registUser => 4,:updateUser => 3,:enable => 1
stock264 = Stock.create :status => "返却",:itemCode => 15,:registUser => 5,:updateUser => 5,:enable => 1
stock265 = Stock.create :status => "棚卸",:itemCode => 13,:registUser => 4,:updateUser => 3,:enable => 1
stock266 = Stock.create :status => "処分",:itemCode => 13,:registUser => 5,:updateUser => 1,:enable => 1
stock267 = Stock.create :status => "返却",:itemCode => 11,:registUser => 1,:updateUser => 3,:enable => 1
stock268 = Stock.create :status => "返却",:itemCode => 13,:registUser => 2,:updateUser => 3,:enable => 1
stock269 = Stock.create :status => "返却",:itemCode => 12,:registUser => 5,:updateUser => 4,:enable => 1
stock270 = Stock.create :status => "棚卸",:itemCode => 14,:registUser => 1,:updateUser => 1,:enable => 1
stock271 = Stock.create :status => "返却",:itemCode => 12,:registUser => 5,:updateUser => 5,:enable => 1
stock272 = Stock.create :status => "棚卸",:itemCode => 12,:registUser => 2,:updateUser => 2,:enable => 1
stock273 = Stock.create :status => "棚卸",:itemCode => 16,:registUser => 3,:updateUser => 1,:enable => 1
stock274 = Stock.create :status => "入荷",:itemCode => 16,:registUser => 4,:updateUser => 2,:enable => 1
stock275 = Stock.create :status => "不明",:itemCode => 17,:registUser => 5,:updateUser => 2,:enable => 1
stock276 = Stock.create :status => "処分",:itemCode => 17,:registUser => 1,:updateUser => 4,:enable => 1
stock277 = Stock.create :status => "返却",:itemCode => 19,:registUser => 3,:updateUser => 2,:enable => 1
stock278 = Stock.create :status => "入荷",:itemCode => 4,:registUser => 1,:updateUser => 5,:enable => 1
stock279 = Stock.create :status => "棚卸",:itemCode => 5,:registUser => 5,:updateUser => 1,:enable => 1
stock280 = Stock.create :status => "棚卸",:itemCode => 4,:registUser => 1,:updateUser => 2,:enable => 1
stock281 = Stock.create :status => "入荷",:itemCode => 2,:registUser => 4,:updateUser => 5,:enable => 1
stock282 = Stock.create :status => "処分",:itemCode => 18,:registUser => 2,:updateUser => 4,:enable => 1
stock283 = Stock.create :status => "返却",:itemCode => 5,:registUser => 3,:updateUser => 1,:enable => 1
stock284 = Stock.create :status => "処分",:itemCode => 5,:registUser => 4,:updateUser => 2,:enable => 1
stock285 = Stock.create :status => "不明",:itemCode => 3,:registUser => 1,:updateUser => 5,:enable => 1
stock286 = Stock.create :status => "返却",:itemCode => 20,:registUser => 2,:updateUser => 3,:enable => 1
stock287 = Stock.create :status => "処分",:itemCode => 2,:registUser => 1,:updateUser => 1,:enable => 1
stock288 = Stock.create :status => "返却",:itemCode => 1,:registUser => 4,:updateUser => 2,:enable => 1
stock289 = Stock.create :status => "処分",:itemCode => 5,:registUser => 4,:updateUser => 2,:enable => 1
stock290 = Stock.create :status => "棚卸",:itemCode => 2,:registUser => 1,:updateUser => 5,:enable => 1
stock291 = Stock.create :status => "不明",:itemCode => 3,:registUser => 4,:updateUser => 5,:enable => 1
stock292 = Stock.create :status => "入荷",:itemCode => 20,:registUser => 4,:updateUser => 1,:enable => 1
stock293 = Stock.create :status => "入荷",:itemCode => 2,:registUser => 5,:updateUser => 2,:enable => 1
stock294 = Stock.create :status => "返却",:itemCode => 3,:registUser => 2,:updateUser => 4,:enable => 1
stock295 = Stock.create :status => "不明",:itemCode => 1,:registUser => 1,:updateUser => 5,:enable => 1
stock296 = Stock.create :status => "返却",:itemCode => 5,:registUser => 5,:updateUser => 3,:enable => 1
stock297 = Stock.create :status => "棚卸",:itemCode => 1,:registUser => 1,:updateUser => 5,:enable => 1
stock298 = Stock.create :status => "入荷",:itemCode => 3,:registUser => 1,:updateUser => 4,:enable => 1
stock299 = Stock.create :status => "不明",:itemCode => 2,:registUser => 1,:updateUser => 2,:enable => 1
stock300 = Stock.create :status => "棚卸",:itemCode => 4,:registUser => 3,:updateUser => 4,:enable => 1
stock301 = Stock.create :status => "棚卸",:itemCode => 13,:registUser => 2,:updateUser => 3,:enable => 1
stock302 = Stock.create :status => "棚卸",:itemCode => 13,:registUser => 2,:updateUser => 5,:enable => 1
stock303 = Stock.create :status => "処分",:itemCode => 11,:registUser => 5,:updateUser => 5,:enable => 1
stock304 = Stock.create :status => "入荷",:itemCode => 12,:registUser => 2,:updateUser => 2,:enable => 1
stock305 = Stock.create :status => "不明",:itemCode => 15,:registUser => 5,:updateUser => 1,:enable => 1
stock306 = Stock.create :status => "返却",:itemCode => 13,:registUser => 4,:updateUser => 3,:enable => 1
stock307 = Stock.create :status => "処分",:itemCode => 12,:registUser => 4,:updateUser => 1,:enable => 1
stock308 = Stock.create :status => "入荷",:itemCode => 14,:registUser => 2,:updateUser => 4,:enable => 1
stock309 = Stock.create :status => "処分",:itemCode => 11,:registUser => 2,:updateUser => 5,:enable => 1
stock310 = Stock.create :status => "返却",:itemCode => 5,:registUser => 5,:updateUser => 2,:enable => 1
stock311 = Stock.create :status => "不明",:itemCode => 1,:registUser => 4,:updateUser => 3,:enable => 1
stock312 = Stock.create :status => "入荷",:itemCode => 2,:registUser => 5,:updateUser => 4,:enable => 1
stock313 = Stock.create :status => "不明",:itemCode => 1,:registUser => 3,:updateUser => 2,:enable => 1
stock314 = Stock.create :status => "不明",:itemCode => 2,:registUser => 4,:updateUser => 1,:enable => 1
stock315 = Stock.create :status => "返却",:itemCode => 5,:registUser => 3,:updateUser => 3,:enable => 1
stock316 = Stock.create :status => "棚卸",:itemCode => 4,:registUser => 3,:updateUser => 1,:enable => 1
stock317 = Stock.create :status => "棚卸",:itemCode => 4,:registUser => 3,:updateUser => 2,:enable => 1
stock318 = Stock.create :status => "不明",:itemCode => 1,:registUser => 4,:updateUser => 3,:enable => 1
stock319 = Stock.create :status => "処分",:itemCode => 4,:registUser => 1,:updateUser => 1,:enable => 1
stock320 = Stock.create :status => "入荷",:itemCode => 1,:registUser => 2,:updateUser => 3,:enable => 1
stock321 = Stock.create :status => "処分",:itemCode => 2,:registUser => 1,:updateUser => 2,:enable => 1
stock322 = Stock.create :status => "返却",:itemCode => 3,:registUser => 4,:updateUser => 2,:enable => 1
stock323 = Stock.create :status => "不明",:itemCode => 1,:registUser => 4,:updateUser => 3,:enable => 1
stock324 = Stock.create :status => "棚卸",:itemCode => 5,:registUser => 4,:updateUser => 4,:enable => 1
stock325 = Stock.create :status => "処分",:itemCode => 1,:registUser => 4,:updateUser => 5,:enable => 1
stock326 = Stock.create :status => "棚卸",:itemCode => 3,:registUser => 1,:updateUser => 4,:enable => 1
stock327 = Stock.create :status => "処分",:itemCode => 1,:registUser => 3,:updateUser => 3,:enable => 1
stock328 = Stock.create :status => "返却",:itemCode => 2,:registUser => 5,:updateUser => 3,:enable => 1
stock329 = Stock.create :status => "返却",:itemCode => 4,:registUser => 3,:updateUser => 2,:enable => 1
stock330 = Stock.create :status => "不明",:itemCode => 5,:registUser => 2,:updateUser => 5,:enable => 1
stock331 = Stock.create :status => "処分",:itemCode => 15,:registUser => 4,:updateUser => 5,:enable => 1
stock332 = Stock.create :status => "不明",:itemCode => 2,:registUser => 5,:updateUser => 1,:enable => 1
stock333 = Stock.create :status => "返却",:itemCode => 3,:registUser => 2,:updateUser => 5,:enable => 1
stock334 = Stock.create :status => "処分",:itemCode => 3,:registUser => 3,:updateUser => 5,:enable => 1
stock335 = Stock.create :status => "棚卸",:itemCode => 2,:registUser => 5,:updateUser => 1,:enable => 1
stock336 = Stock.create :status => "入荷",:itemCode => 5,:registUser => 2,:updateUser => 4,:enable => 1
stock337 = Stock.create :status => "棚卸",:itemCode => 4,:registUser => 1,:updateUser => 4,:enable => 1
stock338 = Stock.create :status => "入荷",:itemCode => 5,:registUser => 2,:updateUser => 4,:enable => 1
stock339 = Stock.create :status => "返却",:itemCode => 5,:registUser => 3,:updateUser => 4,:enable => 1
stock340 = Stock.create :status => "処分",:itemCode => 4,:registUser => 1,:updateUser => 1,:enable => 1
stock341 = Stock.create :status => "返却",:itemCode => 4,:registUser => 5,:updateUser => 4,:enable => 1
stock342 = Stock.create :status => "棚卸",:itemCode => 11,:registUser => 2,:updateUser => 5,:enable => 1
stock343 = Stock.create :status => "処分",:itemCode => 3,:registUser => 1,:updateUser => 5,:enable => 1
stock344 = Stock.create :status => "処分",:itemCode => 5,:registUser => 5,:updateUser => 1,:enable => 1
stock345 = Stock.create :status => "処分",:itemCode => 4,:registUser => 3,:updateUser => 1,:enable => 1
stock346 = Stock.create :status => "入荷",:itemCode => 14,:registUser => 2,:updateUser => 3,:enable => 1
stock347 = Stock.create :status => "処分",:itemCode => 1,:registUser => 4,:updateUser => 5,:enable => 1
stock348 = Stock.create :status => "処分",:itemCode => 3,:registUser => 4,:updateUser => 2,:enable => 1
stock349 = Stock.create :status => "返却",:itemCode => 5,:registUser => 5,:updateUser => 3,:enable => 1
stock350 = Stock.create :status => "処分",:itemCode => 2,:registUser => 2,:updateUser => 2,:enable => 1
stock351 = Stock.create :status => "処分",:itemCode => 3,:registUser => 2,:updateUser => 5,:enable => 1
stock352 = Stock.create :status => "不明",:itemCode => 2,:registUser => 3,:updateUser => 4,:enable => 1
stock353 = Stock.create :status => "不明",:itemCode => 4,:registUser => 5,:updateUser => 1,:enable => 1
stock354 = Stock.create :status => "処分",:itemCode => 3,:registUser => 5,:updateUser => 2,:enable => 1
stock355 = Stock.create :status => "処分",:itemCode => 5,:registUser => 4,:updateUser => 2,:enable => 1
stock356 = Stock.create :status => "入荷",:itemCode => 3,:registUser => 4,:updateUser => 1,:enable => 1
stock357 = Stock.create :status => "処分",:itemCode => 1,:registUser => 2,:updateUser => 2,:enable => 1
stock358 = Stock.create :status => "入荷",:itemCode => 11,:registUser => 5,:updateUser => 2,:enable => 1
stock359 = Stock.create :status => "不明",:itemCode => 5,:registUser => 4,:updateUser => 2,:enable => 1
stock360 = Stock.create :status => "返却",:itemCode => 5,:registUser => 1,:updateUser => 5,:enable => 1
stock361 = Stock.create :status => "処分",:itemCode => 4,:registUser => 4,:updateUser => 4,:enable => 1
stock362 = Stock.create :status => "棚卸",:itemCode => 3,:registUser => 2,:updateUser => 4,:enable => 1
stock363 = Stock.create :status => "不明",:itemCode => 5,:registUser => 3,:updateUser => 4,:enable => 1
stock364 = Stock.create :status => "処分",:itemCode => 3,:registUser => 2,:updateUser => 5,:enable => 1
stock365 = Stock.create :status => "棚卸",:itemCode => 4,:registUser => 3,:updateUser => 2,:enable => 1
stock366 = Stock.create :status => "不明",:itemCode => 3,:registUser => 4,:updateUser => 2,:enable => 1
stock367 = Stock.create :status => "入荷",:itemCode => 3,:registUser => 4,:updateUser => 5,:enable => 1
stock368 = Stock.create :status => "棚卸",:itemCode => 4,:registUser => 1,:updateUser => 1,:enable => 1
stock369 = Stock.create :status => "処分",:itemCode => 12,:registUser => 2,:updateUser => 5,:enable => 1
stock370 = Stock.create :status => "返却",:itemCode => 1,:registUser => 4,:updateUser => 3,:enable => 1
stock371 = Stock.create :status => "入荷",:itemCode => 5,:registUser => 2,:updateUser => 5,:enable => 1
stock372 = Stock.create :status => "処分",:itemCode => 5,:registUser => 1,:updateUser => 2,:enable => 1
stock373 = Stock.create :status => "入荷",:itemCode => 2,:registUser => 3,:updateUser => 5,:enable => 1
stock374 = Stock.create :status => "棚卸",:itemCode => 2,:registUser => 2,:updateUser => 3,:enable => 1
stock375 = Stock.create :status => "不明",:itemCode => 4,:registUser => 3,:updateUser => 5,:enable => 1
stock376 = Stock.create :status => "入荷",:itemCode => 4,:registUser => 2,:updateUser => 5,:enable => 1
stock377 = Stock.create :status => "棚卸",:itemCode => 2,:registUser => 2,:updateUser => 4,:enable => 1
stock378 = Stock.create :status => "返却",:itemCode => 1,:registUser => 2,:updateUser => 4,:enable => 1
stock379 = Stock.create :status => "棚卸",:itemCode => 4,:registUser => 4,:updateUser => 3,:enable => 1
stock380 = Stock.create :status => "入荷",:itemCode => 13,:registUser => 1,:updateUser => 4,:enable => 1
stock381 = Stock.create :status => "返却",:itemCode => 3,:registUser => 1,:updateUser => 5,:enable => 1
stock382 = Stock.create :status => "棚卸",:itemCode => 3,:registUser => 1,:updateUser => 4,:enable => 1
stock383 = Stock.create :status => "棚卸",:itemCode => 3,:registUser => 5,:updateUser => 2,:enable => 1
stock384 = Stock.create :status => "不明",:itemCode => 4,:registUser => 4,:updateUser => 4,:enable => 1
stock385 = Stock.create :status => "棚卸",:itemCode => 2,:registUser => 3,:updateUser => 1,:enable => 1
stock386 = Stock.create :status => "入荷",:itemCode => 1,:registUser => 1,:updateUser => 2,:enable => 1
stock387 = Stock.create :status => "返却",:itemCode => 1,:registUser => 2,:updateUser => 3,:enable => 1
stock388 = Stock.create :status => "不明",:itemCode => 5,:registUser => 4,:updateUser => 4,:enable => 1
stock389 = Stock.create :status => "処分",:itemCode => 4,:registUser => 2,:updateUser => 3,:enable => 1
stock390 = Stock.create :status => "棚卸",:itemCode => 4,:registUser => 4,:updateUser => 2,:enable => 1
stock391 = Stock.create :status => "入荷",:itemCode => 5,:registUser => 5,:updateUser => 4,:enable => 1
stock392 = Stock.create :status => "不明",:itemCode => 5,:registUser => 2,:updateUser => 4,:enable => 1
stock393 = Stock.create :status => "棚卸",:itemCode => 15,:registUser => 4,:updateUser => 4,:enable => 1
stock394 = Stock.create :status => "棚卸",:itemCode => 5,:registUser => 3,:updateUser => 1,:enable => 1
stock395 = Stock.create :status => "入荷",:itemCode => 3,:registUser => 3,:updateUser => 1,:enable => 1
stock396 = Stock.create :status => "入荷",:itemCode => 3,:registUser => 2,:updateUser => 3,:enable => 1
stock397 = Stock.create :status => "不明",:itemCode => 4,:registUser => 2,:updateUser => 4,:enable => 1
stock398 = Stock.create :status => "不明",:itemCode => 3,:registUser => 5,:updateUser => 1,:enable => 1
stock399 = Stock.create :status => "不明",:itemCode => 5,:registUser => 1,:updateUser => 2,:enable => 1
stock400 = Stock.create :status => "処分",:itemCode => 4,:registUser => 3,:updateUser => 1,:enable => 1
stock401 = Stock.create :status => "不明",:itemCode => 4,:registUser => 1,:updateUser => 1,:enable => 1
stock402 = Stock.create :status => "返却",:itemCode => 4,:registUser => 3,:updateUser => 2,:enable => 1
stock403 = Stock.create :status => "返却",:itemCode => 5,:registUser => 4,:updateUser => 3,:enable => 1
stock404 = Stock.create :status => "不明",:itemCode => 13,:registUser => 4,:updateUser => 3,:enable => 1
stock405 = Stock.create :status => "不明",:itemCode => 14,:registUser => 3,:updateUser => 1,:enable => 1
stock406 = Stock.create :status => "返却",:itemCode => 15,:registUser => 4,:updateUser => 4,:enable => 1
stock407 = Stock.create :status => "不明",:itemCode => 15,:registUser => 2,:updateUser => 3,:enable => 1
stock408 = Stock.create :status => "入荷",:itemCode => 12,:registUser => 5,:updateUser => 2,:enable => 1
stock409 = Stock.create :status => "不明",:itemCode => 12,:registUser => 5,:updateUser => 1,:enable => 1
stock410 = Stock.create :status => "棚卸",:itemCode => 11,:registUser => 1,:updateUser => 1,:enable => 1
stock411 = Stock.create :status => "入荷",:itemCode => 12,:registUser => 1,:updateUser => 5,:enable => 1
stock412 = Stock.create :status => "棚卸",:itemCode => 2,:registUser => 3,:updateUser => 2,:enable => 1
stock413 = Stock.create :status => "入荷",:itemCode => 5,:registUser => 4,:updateUser => 1,:enable => 1
stock414 = Stock.create :status => "返却",:itemCode => 1,:registUser => 5,:updateUser => 5,:enable => 1
stock415 = Stock.create :status => "棚卸",:itemCode => 5,:registUser => 2,:updateUser => 5,:enable => 1
stock416 = Stock.create :status => "返却",:itemCode => 1,:registUser => 3,:updateUser => 4,:enable => 1
stock417 = Stock.create :status => "処分",:itemCode => 5,:registUser => 4,:updateUser => 3,:enable => 1
stock418 = Stock.create :status => "棚卸",:itemCode => 3,:registUser => 4,:updateUser => 5,:enable => 1
stock419 = Stock.create :status => "返却",:itemCode => 4,:registUser => 3,:updateUser => 4,:enable => 1
stock420 = Stock.create :status => "入荷",:itemCode => 2,:registUser => 5,:updateUser => 5,:enable => 1
stock421 = Stock.create :status => "棚卸",:itemCode => 3,:registUser => 5,:updateUser => 5,:enable => 1
stock422 = Stock.create :status => "処分",:itemCode => 1,:registUser => 5,:updateUser => 3,:enable => 1
stock423 = Stock.create :status => "入荷",:itemCode => 15,:registUser => 1,:updateUser => 3,:enable => 1
stock424 = Stock.create :status => "返却",:itemCode => 16,:registUser => 1,:updateUser => 4,:enable => 1
stock425 = Stock.create :status => "処分",:itemCode => 17,:registUser => 5,:updateUser => 3,:enable => 1
stock426 = Stock.create :status => "入荷",:itemCode => 16,:registUser => 5,:updateUser => 4,:enable => 1
stock427 = Stock.create :status => "入荷",:itemCode => 17,:registUser => 4,:updateUser => 4,:enable => 1
stock428 = Stock.create :status => "処分",:itemCode => 17,:registUser => 3,:updateUser => 4,:enable => 1
stock429 = Stock.create :status => "返却",:itemCode => 5,:registUser => 4,:updateUser => 1,:enable => 1
stock430 = Stock.create :status => "処分",:itemCode => 4,:registUser => 5,:updateUser => 3,:enable => 1
stock431 = Stock.create :status => "返却",:itemCode => 2,:registUser => 2,:updateUser => 3,:enable => 1
stock432 = Stock.create :status => "入荷",:itemCode => 18,:registUser => 4,:updateUser => 3,:enable => 1
stock433 = Stock.create :status => "入荷",:itemCode => 19,:registUser => 3,:updateUser => 1,:enable => 1
stock434 = Stock.create :status => "入荷",:itemCode => 4,:registUser => 1,:updateUser => 1,:enable => 1
stock435 = Stock.create :status => "入荷",:itemCode => 2,:registUser => 5,:updateUser => 3,:enable => 1
stock436 = Stock.create :status => "返却",:itemCode => 19,:registUser => 1,:updateUser => 5,:enable => 1
stock437 = Stock.create :status => "返却",:itemCode => 3,:registUser => 3,:updateUser => 5,:enable => 1
stock438 = Stock.create :status => "処分",:itemCode => 18,:registUser => 3,:updateUser => 2,:enable => 1
stock439 = Stock.create :status => "不明",:itemCode => 5,:registUser => 5,:updateUser => 4,:enable => 1
stock440 = Stock.create :status => "不明",:itemCode => 5,:registUser => 4,:updateUser => 5,:enable => 1
stock441 = Stock.create :status => "処分",:itemCode => 2,:registUser => 5,:updateUser => 4,:enable => 1
stock442 = Stock.create :status => "不明",:itemCode => 2,:registUser => 5,:updateUser => 3,:enable => 1
stock443 = Stock.create :status => "返却",:itemCode => 3,:registUser => 3,:updateUser => 5,:enable => 1
stock444 = Stock.create :status => "処分",:itemCode => 3,:registUser => 1,:updateUser => 4,:enable => 1
stock445 = Stock.create :status => "入荷",:itemCode => 16,:registUser => 4,:updateUser => 2,:enable => 1
stock446 = Stock.create :status => "返却",:itemCode => 4,:registUser => 5,:updateUser => 4,:enable => 1
stock447 = Stock.create :status => "棚卸",:itemCode => 1,:registUser => 4,:updateUser => 1,:enable => 1
stock448 = Stock.create :status => "返却",:itemCode => 4,:registUser => 5,:updateUser => 2,:enable => 1
stock449 = Stock.create :status => "返却",:itemCode => 4,:registUser => 2,:updateUser => 5,:enable => 1
stock450 = Stock.create :status => "処分",:itemCode => 4,:registUser => 2,:updateUser => 2,:enable => 1
stock451 = Stock.create :status => "返却",:itemCode => 17,:registUser => 5,:updateUser => 3,:enable => 1
stock452 = Stock.create :status => "入荷",:itemCode => 3,:registUser => 2,:updateUser => 1,:enable => 1
stock453 = Stock.create :status => "不明",:itemCode => 2,:registUser => 5,:updateUser => 1,:enable => 1
stock454 = Stock.create :status => "返却",:itemCode => 4,:registUser => 2,:updateUser => 4,:enable => 1
stock455 = Stock.create :status => "返却",:itemCode => 18,:registUser => 2,:updateUser => 2,:enable => 1
stock456 = Stock.create :status => "入荷",:itemCode => 12,:registUser => 2,:updateUser => 2,:enable => 1
stock457 = Stock.create :status => "処分",:itemCode => 5,:registUser => 5,:updateUser => 5,:enable => 1
stock458 = Stock.create :status => "入荷",:itemCode => 4,:registUser => 3,:updateUser => 1,:enable => 1
stock459 = Stock.create :status => "入荷",:itemCode => 5,:registUser => 3,:updateUser => 4,:enable => 1
stock460 = Stock.create :status => "不明",:itemCode => 12,:registUser => 1,:updateUser => 2,:enable => 1
stock461 = Stock.create :status => "不明",:itemCode => 4,:registUser => 3,:updateUser => 5,:enable => 1
stock462 = Stock.create :status => "返却",:itemCode => 5,:registUser => 2,:updateUser => 4,:enable => 1
stock463 = Stock.create :status => "返却",:itemCode => 14,:registUser => 3,:updateUser => 4,:enable => 1
stock464 = Stock.create :status => "不明",:itemCode => 5,:registUser => 5,:updateUser => 2,:enable => 1
stock465 = Stock.create :status => "棚卸",:itemCode => 4,:registUser => 2,:updateUser => 1,:enable => 1
stock466 = Stock.create :status => "棚卸",:itemCode => 4,:registUser => 3,:updateUser => 4,:enable => 1
stock467 = Stock.create :status => "返却",:itemCode => 2,:registUser => 2,:updateUser => 2,:enable => 1
stock468 = Stock.create :status => "処分",:itemCode => 17,:registUser => 3,:updateUser => 2,:enable => 1
stock469 = Stock.create :status => "返却",:itemCode => 4,:registUser => 1,:updateUser => 1,:enable => 1
stock470 = Stock.create :status => "入荷",:itemCode => 5,:registUser => 1,:updateUser => 2,:enable => 1
stock471 = Stock.create :status => "返却",:itemCode => 4,:registUser => 4,:updateUser => 4,:enable => 1
stock472 = Stock.create :status => "棚卸",:itemCode => 5,:registUser => 3,:updateUser => 1,:enable => 1
stock473 = Stock.create :status => "不明",:itemCode => 5,:registUser => 1,:updateUser => 5,:enable => 1
stock474 = Stock.create :status => "入荷",:itemCode => 4,:registUser => 4,:updateUser => 3,:enable => 1
stock475 = Stock.create :status => "棚卸",:itemCode => 3,:registUser => 1,:updateUser => 2,:enable => 1
stock476 = Stock.create :status => "返却",:itemCode => 4,:registUser => 2,:updateUser => 1,:enable => 1
stock477 = Stock.create :status => "不明",:itemCode => 18,:registUser => 5,:updateUser => 3,:enable => 1
stock478 = Stock.create :status => "棚卸",:itemCode => 5,:registUser => 5,:updateUser => 2,:enable => 1
stock479 = Stock.create :status => "棚卸",:itemCode => 5,:registUser => 2,:updateUser => 4,:enable => 1
stock480 = Stock.create :status => "不明",:itemCode => 3,:registUser => 3,:updateUser => 4,:enable => 1
stock481 = Stock.create :status => "処分",:itemCode => 5,:registUser => 2,:updateUser => 1,:enable => 1
stock482 = Stock.create :status => "不明",:itemCode => 3,:registUser => 1,:updateUser => 3,:enable => 1
stock483 = Stock.create :status => "返却",:itemCode => 5,:registUser => 5,:updateUser => 2,:enable => 1
stock484 = Stock.create :status => "棚卸",:itemCode => 19,:registUser => 1,:updateUser => 3,:enable => 1
stock485 = Stock.create :status => "棚卸",:itemCode => 2,:registUser => 4,:updateUser => 3,:enable => 1
stock486 = Stock.create :status => "棚卸",:itemCode => 3,:registUser => 4,:updateUser => 2,:enable => 1
stock487 = Stock.create :status => "返却",:itemCode => 5,:registUser => 3,:updateUser => 5,:enable => 1
stock488 = Stock.create :status => "不明",:itemCode => 2,:registUser => 4,:updateUser => 4,:enable => 1
stock489 = Stock.create :status => "返却",:itemCode => 2,:registUser => 1,:updateUser => 5,:enable => 1
stock490 = Stock.create :status => "返却",:itemCode => 19,:registUser => 1,:updateUser => 2,:enable => 1
stock491 = Stock.create :status => "入荷",:itemCode => 19,:registUser => 2,:updateUser => 2,:enable => 1
stock492 = Stock.create :status => "入荷",:itemCode => 2,:registUser => 1,:updateUser => 1,:enable => 1
stock493 = Stock.create :status => "棚卸",:itemCode => 18,:registUser => 2,:updateUser => 5,:enable => 1
stock494 = Stock.create :status => "返却",:itemCode => 2,:registUser => 4,:updateUser => 2,:enable => 1
stock495 = Stock.create :status => "入荷",:itemCode => 2,:registUser => 3,:updateUser => 5,:enable => 1
stock496 = Stock.create :status => "不明",:itemCode => 4,:registUser => 4,:updateUser => 3,:enable => 1
stock497 = Stock.create :status => "処分",:itemCode => 3,:registUser => 4,:updateUser => 4,:enable => 1
stock498 = Stock.create :status => "返却",:itemCode => 17,:registUser => 2,:updateUser => 2,:enable => 1
stock499 = Stock.create :status => "入荷",:itemCode => 2,:registUser => 3,:updateUser => 4,:enable => 1
stock500 = Stock.create :status => "処分",:itemCode => 16,:registUser => 1,:updateUser => 5,:enable => 1
stock501 = Stock.create :status => "棚卸",:itemCode => 5,:registUser => 3,:updateUser => 1,:enable => 1
stock502 = Stock.create :status => "処分",:itemCode => 5,:registUser => 1,:updateUser => 1,:enable => 1
stock503 = Stock.create :status => "不明",:itemCode => 1,:registUser => 1,:updateUser => 5,:enable => 1
stock504 = Stock.create :status => "返却",:itemCode => 2,:registUser => 3,:updateUser => 1,:enable => 1
stock505 = Stock.create :status => "処分",:itemCode => 16,:registUser => 5,:updateUser => 5,:enable => 1
stock506 = Stock.create :status => "入荷",:itemCode => 16,:registUser => 4,:updateUser => 4,:enable => 1
stock507 = Stock.create :status => "入荷",:itemCode => 2,:registUser => 2,:updateUser => 1,:enable => 1
stock508 = Stock.create :status => "入荷",:itemCode => 2,:registUser => 5,:updateUser => 3,:enable => 1
stock509 = Stock.create :status => "処分",:itemCode => 3,:registUser => 1,:updateUser => 2,:enable => 1
stock510 = Stock.create :status => "処分",:itemCode => 3,:registUser => 1,:updateUser => 5,:enable => 1
stock511 = Stock.create :status => "不明",:itemCode => 2,:registUser => 3,:updateUser => 2,:enable => 1
stock512 = Stock.create :status => "入荷",:itemCode => 17,:registUser => 3,:updateUser => 1,:enable => 1
stock513 = Stock.create :status => "棚卸",:itemCode => 4,:registUser => 2,:updateUser => 1,:enable => 1
stock514 = Stock.create :status => "棚卸",:itemCode => 4,:registUser => 5,:updateUser => 3,:enable => 1
stock515 = Stock.create :status => "入荷",:itemCode => 18,:registUser => 5,:updateUser => 4,:enable => 1
stock516 = Stock.create :status => "棚卸",:itemCode => 2,:registUser => 3,:updateUser => 5,:enable => 1
stock517 = Stock.create :status => "入荷",:itemCode => 19,:registUser => 4,:updateUser => 4,:enable => 1
stock518 = Stock.create :status => "処分",:itemCode => 2,:registUser => 1,:updateUser => 2,:enable => 1
stock519 = Stock.create :status => "処分",:itemCode => 1,:registUser => 5,:updateUser => 1,:enable => 1
stock520 = Stock.create :status => "不明",:itemCode => 20,:registUser => 5,:updateUser => 1,:enable => 1
stock521 = Stock.create :status => "入荷",:itemCode => 4,:registUser => 4,:updateUser => 4,:enable => 1
stock522 = Stock.create :status => "不明",:itemCode => 4,:registUser => 3,:updateUser => 3,:enable => 1
stock523 = Stock.create :status => "処分",:itemCode => 20,:registUser => 2,:updateUser => 3,:enable => 1
stock524 = Stock.create :status => "不明",:itemCode => 20,:registUser => 4,:updateUser => 5,:enable => 1
stock525 = Stock.create :status => "返却",:itemCode => 4,:registUser => 2,:updateUser => 3,:enable => 1
stock526 = Stock.create :status => "入荷",:itemCode => 5,:registUser => 4,:updateUser => 2,:enable => 1
stock527 = Stock.create :status => "返却",:itemCode => 4,:registUser => 1,:updateUser => 4,:enable => 1
stock528 = Stock.create :status => "入荷",:itemCode => 2,:registUser => 4,:updateUser => 3,:enable => 1
stock529 = Stock.create :status => "不明",:itemCode => 2,:registUser => 5,:updateUser => 4,:enable => 1
stock530 = Stock.create :status => "処分",:itemCode => 4,:registUser => 2,:updateUser => 1,:enable => 1
stock531 = Stock.create :status => "棚卸",:itemCode => 1,:registUser => 5,:updateUser => 1,:enable => 1
stock532 = Stock.create :status => "入荷",:itemCode => 2,:registUser => 5,:updateUser => 1,:enable => 1
stock533 = Stock.create :status => "棚卸",:itemCode => 3,:registUser => 1,:updateUser => 3,:enable => 1
stock534 = Stock.create :status => "返却",:itemCode => 2,:registUser => 2,:updateUser => 4,:enable => 1
stock535 = Stock.create :status => "入荷",:itemCode => 4,:registUser => 2,:updateUser => 4,:enable => 1
stock536 = Stock.create :status => "処分",:itemCode => 3,:registUser => 3,:updateUser => 5,:enable => 1
stock537 = Stock.create :status => "入荷",:itemCode => 4,:registUser => 1,:updateUser => 5,:enable => 1
stock538 = Stock.create :status => "不明",:itemCode => 5,:registUser => 3,:updateUser => 1,:enable => 1
stock539 = Stock.create :status => "不明",:itemCode => 5,:registUser => 1,:updateUser => 2,:enable => 1
stock540 = Stock.create :status => "入荷",:itemCode => 2,:registUser => 1,:updateUser => 4,:enable => 1
stock541 = Stock.create :status => "返却",:itemCode => 4,:registUser => 5,:updateUser => 4,:enable => 1
stock542 = Stock.create :status => "棚卸",:itemCode => 2,:registUser => 5,:updateUser => 4,:enable => 1
stock543 = Stock.create :status => "棚卸",:itemCode => 3,:registUser => 4,:updateUser => 1,:enable => 1
stock544 = Stock.create :status => "入荷",:itemCode => 4,:registUser => 1,:updateUser => 4,:enable => 1
stock545 = Stock.create :status => "棚卸",:itemCode => 4,:registUser => 4,:updateUser => 1,:enable => 1
stock546 = Stock.create :status => "処分",:itemCode => 2,:registUser => 4,:updateUser => 5,:enable => 1
stock547 = Stock.create :status => "不明",:itemCode => 1,:registUser => 1,:updateUser => 3,:enable => 1
stock548 = Stock.create :status => "棚卸",:itemCode => 4,:registUser => 5,:updateUser => 4,:enable => 1
stock549 = Stock.create :status => "棚卸",:itemCode => 2,:registUser => 5,:updateUser => 5,:enable => 1
stock550 = Stock.create :status => "返却",:itemCode => 2,:registUser => 5,:updateUser => 1,:enable => 1
