# コンテナ定義
services:
  vue-app:
    container_name: vue-app
    build: .
    volumes:
      - ../src:/src:cached
      - node_modules:/src/node_modules # 2回目以降コメントイン
    working_dir: "/src"
    ports:
      - "8080:3000"
      - "24678:24678"
    tty: true
    environment:
    - HOST=0.0.0.0
    - port=3000
    - CHOKIDAR_USEPOLLING=true
    # command: sh -c "yarn && yarn dev"

  # DBサーバー
  vue-db:
    # コンテナ名
    container_name: vue-db
    image: mysql:8.0
    # コンテナの作成に使用するDockerfileのパス
    # ホスト側のポート:コンテナ側のポートを指定
    ports:
      - "3306:3306"
    # 環境変数の指定
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    # srcディレクトリ内のファイルをコンテナ内の~/var/www/html配下にマウント
    volumes:
      - "./container/db/data:/var/lib/mysql"
      - "./container/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "./container/db/my.conf:/etc/my.conf"

volumes:
  node_modules:
  