# コンテナ定義
services:
  # webサーバー
  laravel-web:
    # コンテナ名
    container_name: "laravel-web"
    # コンテナの作成に使用するDockerfileのパス
    build:
      context: .
      dockerfile: "./container/web/Dockerfile"
    # ホスト側のポート:コンテナ側のポートを指定
    ports:
      - "8080:80"
    # src配下のファイルをコンテナ内の~/va/www/html配下に配置
    volumes:
      - "../src:/var/www/html"

  # PHPサーバー
  laravel-php:
    # コンテナ名
    container_name: "laravel-php"
    # コンテナの作成に使用するDockerfileのパス
    build:
      context: .
      dockerfile: "./container/php/Dockerfile"
    # srcディレクトリ内のファイルをコンテナ内の~/var/www/html配下にマウント
    volumes:
      - "../src:/var/www/html"
      - /var/www/html/storage/framework
      - /var/www/html/vendor

  # DBサーバー
  laravel-db:
    # コンテナ名
    container_name: laravel-db
    image: mysql:8.0
    # コンテナの作成に使用するDockerfileのパス
    # ホスト側のポート:コンテナ側のポートを指定
    ports:
      - "3306:3306"
    # 環境変数の指定
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    # srcディレクトリ内のファイルをコンテナ内の~/var/www/html配下にマウント
    volumes:
      - "./container/db/data:/var/lib/mysql"
      - "./container/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
      - "./container/db/my.conf:/etc/my.conf"